data :
  name: mvtec
  data_dir: datasets/MTD
  category: None
  image_size:  256
  batch_size: 32
  mask : True
  imput_channel : 3


model:
  checkpoint_dir: checkpoints/MDT/
  checkpoint_name: weights
  exp_name: default
  backbone: wide_resnet50_2 #cait_m48_448 wide_resnet50_2
  pre_trained: True
  noise : Gaussian # options : [Gaussian, Perlin]
  schedule : linear # options: [linear, quad, const, jsd, sigmoid]
  learning_rate: 0.001
  weight_decay: 0.00001
  epochs: 400
  trajectory_steps: 301
  test_trajectoy_steps: 300 # 230 cannot reconstruct missed components
  beta_start : 0.0001 # 0.0001
  beta_end : 0.006  # 0.006 for 300
  ema : True
  ema_rate : 0.999
  device: 'cuda' #<"cpu", "gpu", "tpu", "ipu">
  save_model: True
  num_workers : 32
  seed : 42


metrics:
  image_level_F1Score: True
  image_level_AUROC: True
  pixel_level_F1Score: True
  pixel_level_AUROC: True
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null
