data :
  name: mvtec
  data_dir: datasets/MVTec
  category: cable
  image_size:  256
  batch_size: 32


model:
  checkpoint_dir: checkpoints/500/
  checkpoint_name: weights
  exp_name: default
  backbone: wide_resnet50_2 #cait_m48_448 wide_resnet50_2
  pre_trained: True
  noise : Gaussian # options : [Gaussian, Perlin]
  schedule : linear # options: [linear, cosine]
  learning_rate: 0.001
  weight_decay: 0.00001
  epochs: 500
  trajectory_steps: 200
  test_trajectoy_steps: 199 # 230 cannot reconstruct missed components
  device: 'cuda' #<"cpu", "gpu", "tpu", "ipu">
  save_model: True
  num_workers : 32
  seed : 42


metrics:
  image_level_F1Score: True
  image_level_AUROC: True
  pixel_level_F1Score: True
  pixel_level_AUROC: True
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null
