data :
  name: mvtec  #mvtec if the dataset is MVTec AD, otherwise, it is the name of your desire dataset
  data_dir: datasets/MVTec
  category: None
  image_size:  256
  batch_size: 32
  mask : True
  imput_channel : 3


model:
  checkpoint_dir: checkpoints/500250
  checkpoint_name: weights
  exp_name: default
  backbone: wide_resnet50_2 # wide_resnet50_2
  representation_backbone: wide_resnet50_2 # wide_resnet50_2 cait_m48_448
  pre_trained: True
  noise : Gaussian # options : [Gaussian, Perlin]
  schedule : linear # options: [linear, quad, const, jsd, sigmoid]
  learning_rate: 0.001
  weight_decay: 0.00001
  epochs: 1000
  trajectory_steps: 401
  skip : 30
  eta : 0.8
  test_trajectoy_steps: 400 # 230 cannot reconstruct missed components
  beta_start : 0.0001 # 0.0001
  beta_end : 0.007  # 0.006 for 300
  ema : True
  ema_rate : 0.999
  device: 'cuda' #<"cpu", "gpu", "tpu", "ipu">
  save_model: True
  num_workers : 32
  seed : 42


metrics:
  image_level_F1Score: True
  image_level_AUROC: True
  pixel_level_F1Score: True
  pixel_level_AUROC: True
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null
